# version: '3.8' obsolete

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - 8000:8000

  cmd:
    image: ghcr.io/huggingface/neuronx-tgi:latest
    container_name: aviator
    privileged: true
    command: ["--model-id", "/data/$MODEL_PATH-neuron"]
    volumes:
      - /mnt/data:/data
    ports:
      - 8080:80