version: '3'

# Testing env
# 10.212.153.228

services:
  # langflow:
  #   image: garystafford/langflow:0.3.3
  #   ports:
  #     - "7860:7860"
  #   container_name: langflow

  langchain:
    image: langchain_img
    container_name: langchain
    build:
      context: .
      dockerfile: langchain.dockerfile
    volumes:
      - .:/app
    command: python /app/agent.py $OPENAI_API_KEY

    
    
    # python /app/agent.py $OPENAI_API_KEY
    # docker run -v ./:/app/ langchain_img