version: '3'

services:
  langflow:
    image: garystafford/langflow:0.3.3
    ports:
      - "7860:7860"
    container_name: langflow

  langchain:
    container_name: langchain
    build:
      context: .
      dockerfile: langchain.dockerfile
    volumes:
      - ./agent.py:/app/agent.py