# version: '3.8' obsolete

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - 8000:8000
      
  ollama:
    image: ollama/ollama
    container_name: ollama
    # command: ollama run $MODEL
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 8080:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


# https://hub.docker.com/r/ollama/ollama
