# version: '3.8' obsolete

networks:
  net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      # Default configuration for persist_directory in chromadb/config.py
      # Currently default in "/chroma/chroma/"
      - chroma-data:/chroma/chroma/
    ports:
      - 8000:8000
    networks:
      - net
      
  ollama:
    image: ollama/ollama
    container_name: ollama
    # command: ollama run $MODEL
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 8080:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


volumes:
  chroma-data:
    driver: local

# https://hub.docker.com/r/ollama/ollama
